---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Home Page
- type: document
  path: content/home/skills.md
  label: Skills
  match: "**/*"
- type: document
  path: content/home/about.md
  label: About
- type: document
  path: content/authors/admin/_index.md
  label: Personal Info
- type: heading
  label: Courses Section
- type: directory
  path: content/courses
  label: Courses
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.0
