---
label: 0. Course Main
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: linktitle
  label: linktitle
- type: text
  name: summary
  label: summary
- type: number
  name: weight
  label: weight
  default: 1
  hidden: true
- type: datetime
  name: date
  label: date
  config:
    required: false
  default: now
  hidden: true
- type: datetime
  name: lastmod
  label: lastmod
  hidden: true
  default: ''
- type: boolean
  name: toc
  label: toc
  hidden: true
- type: text
  name: type
  label: type
  hidden: true
  default: docs
pages:
- content/courses/datascience/cosc-3337-data-science.md
