---
label: 3. Prerequisite Materials
hide_body: false
fields:
- type: text
  name: title
  label: title
  default: Prerequisite Materials Save
  hidden: true
- type: text
  name: linktitle
  label: linktitle
  default: Prerequisite Materials Save
  hidden: true
- type: boolean
  name: toc
  label: toc
  default: false
  hidden: true
- type: text
  name: type
  label: type
  default: docs
  hidden: true
- type: datetime
  name: date
  label: date
  default: now
  hidden: true
- type: number
  name: weight
  label: weight
  hidden: true
  default: 3
