---
label: 4. FAQ
hide_body: false
fields:
- type: text
  name: title
  label: title
  default: FAQ
  hidden: true
- type: text
  name: linktitle
  label: linktitle
  default: FAQ
  hidden: true
- type: boolean
  name: toc
  label: toc
  hidden: true
- type: text
  name: type
  label: type
  default: docs
  hidden: true
- type: datetime
  name: date
  label: date
  config:
    required: false
  default: now
  hidden: true
- type: number
  name: weight
  label: weight
  default: 4
  hidden: true
