---
label: 6. Group Assignments
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: linktitle
  label: linktitle
- type: boolean
  name: toc
  label: toc
- type: text
  name: type
  label: type
- type: datetime
  name: date
  label: date
- type: number
  name: weight
  label: weight
